#theme: jekyll-theme-cayman
remote_theme: nrandecker/particle
#title: Rafael Oliveira
#description: Sou desenvolvedor web e mobile.

username : Rafael Oliveira 
user_description : "Programador Web e Mobile, conhecimentos nas linguagens ou tecnologias: Java, C#, Javascript, CSS e HTML."
user_title : "Programador Fullstack"
email : rafael_dso@hotmail.com
twitter_username: "@rafael_diego"
github_username:  "github.com/rafaeldso"
gplus_username:  "@Rafael_Oliveira"
